### ISSUE TITLE
Error on login 

### ISSUE THREAD

**Issue by dabadoo** [doadin/PlexusStatusRD_PvP#1]
Describe the bug
Doesn't work classic era. 2 errors on login.

To Reproduce

    Disable all addons except plexus + this plugin + bugsack/bugrabber
    Login
    fatality (2 errors)

Screenshots

Desktop (please complete the following information):

    Windows
    v1.1.7-classic
    Classic Era

Additional context

		{
			["message"] = "Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:519: attempt to index a nil value",
			["time"] = "2023/08/13 22:59:03",
			["locals"] = "self = <table> {\n ScanUnit = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:362\n SetDefaultModuleLibraries = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:363\n options = <table> {\n }\n Enable = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:290\n NewModule = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:231\n CheckDetectZone = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:211\n EnableModule = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:328\n modules = <table> {\n }\n CancelTimer = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceTimer-3.0\\AceTimer-3.0.lua:147\n IterateEmbeds = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:438\n baseName = \"PlexusStatusRaidDebuff\"\n LoadZoneDebuff = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:605\n defaultModuleLibraries = <table> {\n }\n TimeLeft = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceTimer-3.0\\AceTimer-3.0.lua:172\n GetName = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:275\n CreateZoneMenu = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:798\n RegisterCustomDebuff = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:951\n ScheduleRepeatingTimer = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceTimer-3.0\\AceTimer-3.0.lua:129\n CancelAllTimers = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceTimer-3.0\\AceTimer-3.0.lua:160\n LoadZoneMenu = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:590\n BossNameId = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:568\n SetDefaultModulePrototype = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:405\n BossNameLocale = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:528\n DebuffId = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:518\n Grid_UnitJoined = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:297\n name = \"Plexus_PlexusStatus_GridStatusRaidDebuff\"\n DebuffLocale = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:464\n IsEnabled = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:447\n orderedModules = <table> {\n }\n ScheduleTimer = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceTimer-3.0\\AceTimer-3.0.lua:94\n DisableModule = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:346\n ScanNewDebuff = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:321\n defaultDB = <table> {\n }\n RegisterStatuses = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:288\n UpdateAllUnits = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:315\n RegisterMessage = <function> defined @Interface\\AddOns\\BugSack\\Libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:80\n UnregisterMessage = <function> defined @Interface\\AddOns\\BugSack\\Libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:143\n UnregisterAllEvents = <function> defined @Interface\\AddOns\\BugSack\\Libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:164\n GetModule = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:206\n UpdateRefresh = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:283\n super = <table> {\n }\n Disable = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:310\n IsModule = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:213\n db = <table> {\n }\n SetDefaultModuleState = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:383\n PLAYER_ENTERING_WORLD = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:206\n ZoneCheck = <function> defined @Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua:225\n SetEnabledState = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:420\n OnEnable = ",
			["stack"] = "[string \"@Interface\\AddOns\\PlexusStatusRaidDebuff\\Core.lua\"]:519: in function `DebuffId'\n[string \"@Interface\\AddOns\\PlexusStatusRD_PvP\\AlteracValley.lua\"]:9: in main chunk",
			["session"] = 4922,
			["counter"] = 10,
		}, -- [1]
		{
			["message"] = " (null)",
			["time"] = "2023/08/13 22:59:03",
			["session"] = 4922,
			["counter"] = 7,
		}, -- [2]
	},

**Comment by doadin** [comment]
should be fixed: https://github.com/doadin/PlexusStatusRD_PvP/commit/fccce4ed72a22e29217f021bdb466e52f30b1aa2 look for version 1.1.8 or later.
